apiVersion: apps/v1
kind: ResourceQuota
metadata:
  name: workers-resources
  labels:
    app: kubenews-app
spec:
  hard:
    pods: "10"
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi