services:
  # Serviço da aplicação Kube-News
  app:
    image: rukasu/labk8s-kubenews:v1.5
    build:
      context: ./src
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_DATABASE=kubedevnews
      - DB_USERNAME=kubedevnews
      - DB_PASSWORD=Pg#123
      - DB_SSL_REQUIRE=false
    depends_on:
      - postgres
    networks:
      - kube-news-network

  # Serviço do PostgreSQL
  postgres:
    image: postgres:17.5-alpine3.22
    container_name: kube-news-db
    environment:
      - POSTGRES_DB=kubedevnews
      - POSTGRES_USER=kubedevnews
      - POSTGRES_PASSWORD=Pg#123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - kube-news-network

  postgres_exporter:
    image: quay.io/prometheuscommunity/postgres-exporter:latest
    container_name: postgres_exporter
    restart: always
    depends_on:
      - postgres
    environment:
      DATA_SOURCE_URI: "postgres:5432/mydb?sslmode=disable"
      DATA_SOURCE_USER: kubedevnews
      DATA_SOURCE_PASS: Pg#123
    ports:
      - "9187:9187"  # Porta padrão do exporter

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

volumes:
  postgres_data:

networks:
  kube-news-network:
    driver: bridge
