global:
  scrape_interval: "15s"
  scrape_timeout: "10s"
  evaluation_interval: "15s"
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets:
          - localhost:9090
    metrics_path: /metrics
    honor_labels: false
    honor_timestamps: true
    scheme: http
    follow_redirects: true
    body_size_limit: "0"
    sample_limit: 0
    label_limit: 0
    label_name_length_limit: 0
    label_value_length_limit: 0
    target_limit: 0

  - job_name: 'app'
    scrape_interval: 5s
    scrape_timeout: 2s
    static_configs:
      - targets:
          - app:8080
    metrics_path: /metrics
    scheme: http

  - job_name: 'postgres'
    scrape_interval: 5s
    scrape_timeout: 2s
    static_configs:
      - targets:
          - postgres_exporter:9187
        labels:
          database: postgres