name: Kube-News Manual Workflow

on:
    workflow_call: 
    workflow_dispatch:

jobs:
    Hadolint-Check:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Run Hadolint
              uses: hadolint/hadolint-action@v3.1.0
              with:
                dockerfile: 02-kube-news/Dockerfile

    Scan:
        needs: Hadolint-Check
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Build image for scanning
              run: cd 02-kube-news/ && docker build -t temp-kubenews:latest
              
            - name: Scan with Trivy
              uses: aquasecurity/trivy-action@0.32.0
              with:
                image-ref: temp-kubenews:latest
                format: table
                exit-code: 1
                severity: CRITICAL,HIGH

    Build-Push-Sign:
        needs: Scan
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ vars.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_TOKEN }}
            
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3
            
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
      
            - name: Build and push
              uses: docker/build-push-action@v6
              with:
                context: 02-kube-news/
                push: true
                tags: |
                    ${{ vars.DOCKER_USERNAME }}/labk8s-kubenews:latest
                    ${{ vars.DOCKER_USERNAME }}/labk8s-kubenews:v${{ github.run_number }}

            - name: Install Cosign
              uses: sigstore/cosign-installer@v3.9.1

            - name: Sign image with Cosign
              env:
                COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
              run: cosign sign --key env://COSIGN_PRIVATE_KEY \
                     ${{ secrets.DOCKER_USERNAME }}/labk8s-kubenews:${{ github.run_number }}
    